/* magna_server_config.h

 Generated by phxrpc_pb2server from magna.proto

*/

#pragma once

#include "phxrpc/rpc.h"


class MagnaServerConfig {
  public:
    MagnaServerConfig();

    virtual ~MagnaServerConfig();

    bool Read(const char *config_file);

    phxrpc::HshaServerConfig &GetHshaServerConfig();

  private:
    phxrpc::HshaServerConfig ep_server_config_;
};

