/* simu_tool_impl.cpp

 Generated by phxrpc_pb2tool from simu.proto

*/

#include "simu_tool_impl.h"

#include "simu_client.h"

#include "phxrpc/file.h"


using namespace phxrpc;


SimuToolImpl::SimuToolImpl() {
}

SimuToolImpl::~SimuToolImpl() {
}

int SimuToolImpl::PhxMqttConnect(phxrpc::OptMap &opt_map) {
    phxrpc::MqttConnectPb req;
    phxrpc::MqttConnackPb resp;


    SimuClient client;
    int ret{client.PhxMqttConnect(req, &resp)};
    printf("%s return %d\n", __func__, ret);
    printf("resp: {\n%s}\n", resp.DebugString().c_str());

    return ret;
}

int SimuToolImpl::PhxMqttPublish(phxrpc::OptMap &opt_map) {
    phxrpc::MqttPublishPb req;
    phxrpc::MqttPubackPb resp;

    if (nullptr == opt_map.Get('s')) return -1;

    req.set_content(opt_map.Get('s'));

    SimuClient client;
    int ret{client.PhxMqttPublish(req, &resp)};
    printf("%s return %d\n", __func__, ret);
    printf("resp: {\n%s}\n", resp.DebugString().c_str());

    return ret;
}

int SimuToolImpl::PhxMqttDisconnect(phxrpc::OptMap &opt_map) {
    phxrpc::MqttDisconnectPb req;


    SimuClient client;
    int ret{client.PhxMqttDisconnect(req)};
    printf("%s return %d\n", __func__, ret);

    return ret;
}


int SimuToolImpl::PhxEcho(phxrpc::OptMap &opt_map) {
    google::protobuf::StringValue req;
    google::protobuf::StringValue resp;

    if (nullptr == opt_map.Get('s')) return -1;

    req.set_value(opt_map.Get('s'));

    SimuClient client;
    int ret{client.PhxEcho(req, &resp)};
    printf("%s return %d\n", __func__, ret);
    printf("resp: {\n%s}\n", resp.DebugString().c_str());

    return ret;
}

int SimuToolImpl::GetRet(phxrpc::OptMap &opt_map) {
    magna::RetRequest req;
    magna::RetResponse resp;

    // TODO: fill req from opt_map

    SimuClient client;
    int ret{client.GetRet(req, &resp)};
    printf("%s return %d\n", __func__, ret);
    printf("resp: {\n%s}\n", resp.DebugString().c_str());

    return ret;
}

int SimuToolImpl::ReportLoad(phxrpc::OptMap &opt_map) {
    magna::ReportLoadRequest req;
    magna::ReportLoadResponse resp;

    // TODO: fill req from opt_map

    SimuClient client;
    int ret{client.ReportLoad(req, &resp)};
    printf("%s return %d\n", __func__, ret);
    printf("resp: {\n%s}\n", resp.DebugString().c_str());

    return ret;
}

