/* simu_service_impl.h

 Generated by phxrpc_pb2service from simu.proto

*/

#pragma once

#include "simu.pb.h"
#include "phxrpc_simu_service.h"


class SimuServerConfig;


typedef struct tagServiceArgs {
    SimuServerConfig *config;
    //You can add other arguments here and initiate in main().
} ServiceArgs_t;


class SimuServiceImpl : public SimuService {
  public:
    SimuServiceImpl(ServiceArgs_t &app_args);
    virtual ~SimuServiceImpl();

    virtual int PhxMqttConnect(const phxrpc::MqttConnectPb &req, phxrpc::MqttConnackPb *resp) override;
    virtual int PhxMqttPublish(const phxrpc::MqttPublishPb &req, phxrpc::MqttPubackPb *resp) override;
    virtual int PhxMqttDisconnect(const phxrpc::MqttDisconnectPb &req) override;

    virtual int PhxEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) override;
    virtual int GetRet(const magna::RetRequest &req, magna::RetResponse *resp) override;
    virtual int ReportLoad(const magna::ReportLoadRequest &req, magna::ReportLoadResponse *resp) override;

  private:
    ServiceArgs_t &args_;
};

