/* simu_server_config.h

 Generated by phxrpc_pb2server from simu.proto

*/

#pragma once

#include "phxrpc/rpc.h"


class SimuServerConfig {
  public:
    SimuServerConfig();

    virtual ~SimuServerConfig();

    bool Read(const char *config_file);

    phxrpc::HshaServerConfig &GetHshaServerConfig();

  private:
    phxrpc::HshaServerConfig ep_server_config_;
};

