/* simu_tool_impl.h

 Generated by phxrpc_pb2tool from simu.proto

*/

#pragma once

#include "phxrpc_simu_tool.h"

#include <cstdio>


namespace phxrpc {


class OptMap;


}


class SimuToolImpl : public SimuTool {
  public:
    SimuToolImpl();
    virtual ~SimuToolImpl();

    virtual int PhxMqttConnect(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttPublish(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttDisconnect(phxrpc::OptMap &opt_map) override;
    virtual int PhxEcho(phxrpc::OptMap &opt_map) override;
    virtual int GetRet(phxrpc::OptMap &opt_map) override;
    virtual int ReportLoad(phxrpc::OptMap &opt_map) override;
};

