/* simu_server_config.cpp

 Generated by phxrpc_pb2server from simu.proto

*/

#include "simu_server_config.h"

#include "simu.pb.h"


SimuServerConfig::SimuServerConfig() {
}

SimuServerConfig::~SimuServerConfig() {
}

bool SimuServerConfig::Read(const char *config_file) {
    bool ret{ep_server_config_.Read(config_file)};

    if (0 == strlen(ep_server_config_.GetPackageName())) {
        ep_server_config_.SetPackageName(
magna::RetRequest::default_instance().GetDescriptor()->file()->package().c_str());
    }

    return ret;
}

phxrpc::HshaServerConfig &SimuServerConfig::GetHshaServerConfig() {
    return ep_server_config_;
}

