/* search_service_impl.h

 Generated by phxrpc_pb2service from search.proto

*/

#pragma once

#include "search.pb.h"
#include "phxrpc_search_service.h"

class SearchServerConfig;

typedef struct tagServiceArgs {
    SearchServerConfig * config;
    //You can add other arguments here and initiate in main().
}ServiceArgs_t;

class SearchServiceImpl : public SearchService
{
public:
    SearchServiceImpl( ServiceArgs_t & app_args );
    virtual ~SearchServiceImpl();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int Search( const search::SearchRequest & req,
        search::SearchResult * resp );

    virtual int Notify( const google::protobuf::StringValue & req,
        google::protobuf::Empty * resp );

private:
    ServiceArgs_t & args_;
};

