/* search_tool_impl.h

 Generated by phxrpc_pb2tool from search.proto

*/

#pragma once

#include "phxrpc_search_tool.h"

#include <cstdio>


namespace phxrpc {


class OptMap;


}


class SearchToolImpl : public SearchTool {
  public:
    SearchToolImpl();
    virtual ~SearchToolImpl();

    virtual int PhxMqttConnect(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttPublish(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttDisconnect(phxrpc::OptMap &opt_map) override;
    virtual int PhxEcho(phxrpc::OptMap &opt_map) override;
    virtual int Search(phxrpc::OptMap &opt_map) override;
    virtual int Notify(phxrpc::OptMap &opt_map) override;
};

