/* search_server_config.cpp

 Generated by phxrpc_pb2server from search.proto

*/

#include "search.pb.h"
#include "search_server_config.h"

SearchServerConfig :: SearchServerConfig()
{
}

SearchServerConfig :: ~SearchServerConfig()
{
}

bool SearchServerConfig :: Read( const char * config_file )
{
    bool ret = ep_server_config_.Read( config_file );

    if ( strlen( ep_server_config_.GetPackageName() ) == 0 ) {
        ep_server_config_.SetPackageName( 
search::SearchRequest::default_instance().GetDescriptor()->file()->package().c_str() );
    }

    return ret;
}

phxrpc::HshaServerConfig & SearchServerConfig :: GetHshaServerConfig()
{
    return ep_server_config_;
}
