/* search_tool_main.cpp

 Generated by phxrpc_pb2tool from search.proto

*/

#include <time.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>

#include "phxrpc_search_tool.h"
#include "search_tool_impl.h"

#include "search_client.h"

#include "phxrpc/file.h"

using namespace phxrpc;

void showUsage( const char * program )
{
    printf( "\nUsage: %s [-c <config>] [-f <func>] [-v]\n", program );

    SearchTool::Name2Func_t * name2func = SearchTool::GetName2Func();

    for( int i = 0; ; i++ ) {
        SearchTool::Name2Func_t * iter = &( name2func[i] );

        if( NULL == iter->name ) break;

        printf( "    -f %s %s\n", iter->name, iter->usage );
    }
    printf( "\n" );
    exit( 0 );
}

int main( int argc, char * argv[] )
{
    const char * func = NULL;
    const char * config = NULL;

    for( int i = 1; i < argc - 1; i++ ) {
        if( 0 == strcmp( argv[i], "-c" ) ) {
            config = argv[ ++i ];
        }
        if( 0 == strcmp( argv[i], "-f" ) ) {
            func = argv[ ++i ];
        }
        if( 0 == strcmp( argv[i], "-v" ) ) {
            showUsage( argv[0] );
        }
    }

    if( NULL == func ) showUsage( argv[0] );

    if( NULL != config ) SearchClient::Init( config );

    SearchTool::Name2Func_t * target = NULL;

    SearchTool::Name2Func_t * name2func = SearchTool::GetName2Func();

    for( int i = 0; i < 100; i++ ) {
        SearchTool::Name2Func_t * iter = &( name2func[i] );

        if( NULL == iter->name ) break;

        if( 0 == strcasecmp( func, iter->name ) ) {
            target = iter;
            break;
        }
    }

    if( NULL == target ) showUsage( argv[0] );

    OptMap opt_map( target->opt_string );

    if( ! opt_map.Parse( argc, argv ) ) showUsage( argv[0] );

    SearchTool::ToolFunc_t targefunc = target->func;

    SearchToolImpl tool;

    if( 0 != ( tool.*targefunc ) ( opt_map ) ) showUsage( argv[0] );

    return 0;
}
