/* comp_server_config.h

 Generated by phxrpc_pb2server from comp.proto

*/

#pragma once

#include "phxrpc/rpc.h"


class CompServerConfig {
  public:
    CompServerConfig();

    virtual ~CompServerConfig();

    bool Read(const char *config_file);

    phxrpc::HshaServerConfig &GetHshaServerConfig();

  private:
    phxrpc::HshaServerConfig ep_server_config_;
};

