/* comp_server_config.cpp

 Generated by phxrpc_pb2server from comp.proto

*/

#include "comp_server_config.h"

#include "comp.pb.h"


CompServerConfig::CompServerConfig() {
}

CompServerConfig::~CompServerConfig() {
}

bool CompServerConfig::Read(const char *config_file) {
    bool ret{ep_server_config_.Read(config_file)};

    if (0 == strlen(ep_server_config_.GetPackageName())) {
        ep_server_config_.SetPackageName(
magna::AppRequest::default_instance().GetDescriptor()->file()->package().c_str());
    }

    return ret;
}

phxrpc::HshaServerConfig &CompServerConfig::GetHshaServerConfig() {
    return ep_server_config_;
}

