/* comp_service_impl.cpp

 Generated by phxrpc_pb2service from comp.proto

*/

#include "comp_service_impl.h"

#include "comp_server_config.h"
#include "comp.pb.h"
#include "phxrpc/file.h"


CompServiceImpl::CompServiceImpl(ServiceArgs_t &app_args)
    : args_(app_args) {
}

CompServiceImpl::~CompServiceImpl() {
}

int CompServiceImpl::PhxMqttConnect(const phxrpc::MqttConnectPb &req, phxrpc::MqttConnackPb *resp) {
    return 0;
}

int CompServiceImpl::PhxMqttPublish(const phxrpc::MqttPublishPb &req, phxrpc::MqttPubackPb *resp) {
    // TODO: process req.content()

    return -1;
}

int CompServiceImpl::PhxMqttDisconnect(const phxrpc::MqttDisconnectPb &req) {
    return 0;
}

int CompServiceImpl::PhxEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    resp->set_value(req.value());

    return 0;
}


