/* comp_tool_impl.cpp

 Generated by phxrpc_pb2tool from comp.proto

*/

#include "comp_tool_impl.h"

#include "comp_client.h"

#include "phxrpc/file.h"


using namespace phxrpc;


CompToolImpl::CompToolImpl() {
}

CompToolImpl::~CompToolImpl() {
}

int CompToolImpl::PhxMqttConnect(phxrpc::OptMap &opt_map) {
    phxrpc::MqttConnectPb req;
    phxrpc::MqttConnackPb resp;


    CompClient client;
    int ret{client.PhxMqttConnect(req, &resp)};
    printf("%s return %d\n", __func__, ret);
    printf("resp: {\n%s}\n", resp.DebugString().c_str());

    return ret;
}

int CompToolImpl::PhxMqttPublish(phxrpc::OptMap &opt_map) {
    phxrpc::MqttPublishPb req;
    phxrpc::MqttPubackPb resp;

    if (nullptr == opt_map.Get('s')) return -1;

    req.set_content(opt_map.Get('s'));

    CompClient client;
    int ret{client.PhxMqttPublish(req, &resp)};
    printf("%s return %d\n", __func__, ret);
    printf("resp: {\n%s}\n", resp.DebugString().c_str());

    return ret;
}

int CompToolImpl::PhxMqttDisconnect(phxrpc::OptMap &opt_map) {
    phxrpc::MqttDisconnectPb req;


    CompClient client;
    int ret{client.PhxMqttDisconnect(req)};
    printf("%s return %d\n", __func__, ret);

    return ret;
}


int CompToolImpl::PhxEcho(phxrpc::OptMap &opt_map) {
    google::protobuf::StringValue req;
    google::protobuf::StringValue resp;

    if (nullptr == opt_map.Get('s')) return -1;

    req.set_value(opt_map.Get('s'));

    CompClient client;
    int ret{client.PhxEcho(req, &resp)};
    printf("%s return %d\n", __func__, ret);
    printf("resp: {\n%s}\n", resp.DebugString().c_str());

    return ret;
}

int CompToolImpl::Handle(phxrpc::OptMap &opt_map) {
    magna::AppRequest req;
    magna::AppResponse resp;

    // TODO: fill req from opt_map

    CompClient client;
    int ret{client.Handle(req, &resp)};
    printf("%s return %d\n", __func__, ret);
    printf("resp: {\n%s}\n", resp.DebugString().c_str());

    return ret;
}

