/* comp_tool_impl.h

 Generated by phxrpc_pb2tool from comp.proto

*/

#pragma once

#include "phxrpc_comp_tool.h"

#include <cstdio>


namespace phxrpc {


class OptMap;


}


class CompToolImpl : public CompTool {
  public:
    CompToolImpl();
    virtual ~CompToolImpl();

    virtual int PhxMqttConnect(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttPublish(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttDisconnect(phxrpc::OptMap &opt_map) override;
    virtual int PhxEcho(phxrpc::OptMap &opt_map) override;
    virtual int Handle(phxrpc::OptMap &opt_map) override;
};

