/* comp_client.cpp

 Generated by phxrpc_pb2client from comp.proto

*/

#include "comp_client_uthread.h"

#include <cstdlib>
#include <iostream>
#include <memory>
#include <mutex>

#include "phxrpc_comp_stub.h"

#include "phxrpc/rpc.h"


static phxrpc::ClientConfig global_compclientuthread_config_;
static phxrpc::ClientMonitorPtr global_compclientuthread_monitor_;


bool CompClientUThread::Init(const char *config_file) {
    return global_compclientuthread_config_.Read(config_file);
}

const char *CompClientUThread::GetPackageName() {
    const char *ret = global_compclientuthread_config_.GetPackageName();
    if (strlen(ret) == 0) {
        ret = "magna";
    }
    return ret;
}

CompClientUThread::CompClientUThread(phxrpc::UThreadEpollScheduler *uthread_scheduler) {
    uthread_scheduler_ = uthread_scheduler;
    static std::mutex monitor_mutex;
    if (!global_compclientuthread_monitor_.get()) {
        monitor_mutex.lock();
        if (!global_compclientuthread_monitor_.get()) {
            global_compclientuthread_monitor_ = phxrpc::MonitorFactory::GetFactory()
                ->CreateClientMonitor(GetPackageName());
        }
        global_compclientuthread_config_.SetClientMonitor(global_compclientuthread_monitor_);
        monitor_mutex.unlock();
    }
}

CompClientUThread::~CompClientUThread() {
}

int CompClientUThread::PhxMqttConnect(const phxrpc::MqttConnectPb &req, phxrpc::MqttConnackPb *resp) {
    const phxrpc::Endpoint_t *ep = global_compclientuthread_config_.GetRandom();

    if (uthread_scheduler_ != nullptr && ep != nullptr) {
        phxrpc::UThreadTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(uthread_scheduler_, &socket, ep->ip, ep->port,
                    global_compclientuthread_config_.GetConnectTimeoutMS(),
                    *(global_compclientuthread_monitor_.get()));
        if (open_ret) {
            socket.SetTimeout(global_compclientuthread_config_.GetSocketTimeoutMS());

            CompStub stub(socket, *(global_compclientuthread_monitor_.get()));
            return stub.PhxMqttConnect(req, resp);
        }
    }

    return -1;
}

int CompClientUThread::PhxMqttPublish(const phxrpc::MqttPublishPb &req, phxrpc::MqttPubackPb *resp) {
    const phxrpc::Endpoint_t *ep = global_compclientuthread_config_.GetRandom();

    if (uthread_scheduler_ != nullptr && ep != nullptr) {
        phxrpc::UThreadTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(uthread_scheduler_, &socket, ep->ip, ep->port,
                    global_compclientuthread_config_.GetConnectTimeoutMS(),
                    *(global_compclientuthread_monitor_.get()));
        if (open_ret) {
            socket.SetTimeout(global_compclientuthread_config_.GetSocketTimeoutMS());

            CompStub stub(socket, *(global_compclientuthread_monitor_.get()));
            return stub.PhxMqttPublish(req, resp);
        }
    }

    return -1;
}

int CompClientUThread::PhxMqttDisconnect(const phxrpc::MqttDisconnectPb &req) {
    const phxrpc::Endpoint_t *ep = global_compclientuthread_config_.GetRandom();

    if (uthread_scheduler_ != nullptr && ep != nullptr) {
        phxrpc::UThreadTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(uthread_scheduler_, &socket, ep->ip, ep->port,
                    global_compclientuthread_config_.GetConnectTimeoutMS(),
                    *(global_compclientuthread_monitor_.get()));
        if (open_ret) {
            socket.SetTimeout(global_compclientuthread_config_.GetSocketTimeoutMS());

            CompStub stub(socket, *(global_compclientuthread_monitor_.get()));
            return stub.PhxMqttDisconnect(req);
        }
    }

    return -1;
}

int CompClientUThread::PhxEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    const phxrpc::Endpoint_t *ep = global_compclientuthread_config_.GetRandom();

    if (uthread_scheduler_ != nullptr && ep != nullptr) {
        phxrpc::UThreadTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(uthread_scheduler_, &socket, ep->ip, ep->port,
                    global_compclientuthread_config_.GetConnectTimeoutMS(),
                    *(global_compclientuthread_monitor_.get()));
        if (open_ret) {
            socket.SetTimeout(global_compclientuthread_config_.GetSocketTimeoutMS());

            CompStub stub(socket, *(global_compclientuthread_monitor_.get()));
            return stub.PhxEcho(req, resp);
        }
    }

    return -1;
}

int CompClientUThread::PhxBatchEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    int ret = -1;
    size_t echo_server_count = 2;
    uthread_begin;
    for (size_t i{0}; echo_server_count > i; ++i) {
        uthread_t [=, &uthread_s, &ret](void *) {
            const phxrpc::Endpoint_t *ep = global_compclientuthread_config_.GetByIndex(i);
            if (ep != nullptr) {
                phxrpc::UThreadTcpStream socket;
                if(phxrpc::PhxrpcTcpUtils::Open(&uthread_s, &socket, ep->ip, ep->port,
                            global_compclientuthread_config_.GetConnectTimeoutMS(), *(global_compclientuthread_monitor_.get()))) {
                    socket.SetTimeout(global_compclientuthread_config_.GetSocketTimeoutMS());
                    CompStub stub(socket, *(global_compclientuthread_monitor_.get()));
                    int this_ret = stub.PhxEcho(req, resp);
                    if (this_ret == 0) {
                        ret = this_ret;
                        uthread_s.Close();
                    }
                }
            }
        };
    }
    uthread_end;
    return ret;
}

int CompClientUThread::Handle(const magna::AppRequest &req, magna::AppResponse *resp) {
    const phxrpc::Endpoint_t *ep = global_compclientuthread_config_.GetRandom();

    if (uthread_scheduler_ != nullptr && ep != nullptr) {
        phxrpc::UThreadTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(uthread_scheduler_, &socket, ep->ip, ep->port,
                    global_compclientuthread_config_.GetConnectTimeoutMS(),
                    *(global_compclientuthread_monitor_.get()));
        if (open_ret) {
            socket.SetTimeout(global_compclientuthread_config_.GetSocketTimeoutMS());

            CompStub stub(socket, *(global_compclientuthread_monitor_.get()));
            return stub.Handle(req, resp);
        }
    }

    return -1;
}

int CompClientUThread::Handle(const phxrpc::Endpoint_t &ep, const magna::AppRequest &req, magna::AppResponse *resp)
{
	if (uthread_scheduler_ != nullptr) {
		phxrpc::UThreadTcpStream socket;
		bool open_ret = phxrpc::PhxrpcTcpUtils::Open(uthread_scheduler_, &socket, ep.ip, ep.port,
			global_compclientuthread_config_.GetConnectTimeoutMS(),
			*(global_compclientuthread_monitor_.get()));
		if (open_ret) {
			socket.SetTimeout(global_compclientuthread_config_.GetSocketTimeoutMS());

			CompStub stub(socket, *(global_compclientuthread_monitor_.get()));
			return stub.Handle(req, resp);
		}
	}

	return -1;
}

