/* comp_service_impl.h

 Generated by phxrpc_pb2service from comp.proto

*/

#pragma once

#include "comp.pb.h"
#include "phxrpc_comp_service.h"


class CompServerConfig;


typedef struct tagServiceArgs {
    CompServerConfig *config;
    //You can add other arguments here and initiate in main().
} ServiceArgs_t;


class CompServiceImpl : public CompService {
  public:
    CompServiceImpl(ServiceArgs_t &app_args);
    virtual ~CompServiceImpl();

    virtual int PhxMqttConnect(const phxrpc::MqttConnectPb &req, phxrpc::MqttConnackPb *resp) override;
    virtual int PhxMqttPublish(const phxrpc::MqttPublishPb &req, phxrpc::MqttPubackPb *resp) override;
    virtual int PhxMqttDisconnect(const phxrpc::MqttDisconnectPb &req) override;

    virtual int PhxEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) override;
    virtual int Handle(const magna::AppRequest &req, magna::AppResponse *resp) override;

  private:
    ServiceArgs_t &args_;
};

