/* node_service_impl.h

 Generated by phxrpc_pb2service from node.proto

*/

#pragma once

#include "node.pb.h"
#include "phxrpc_node_service.h"

class NodeServerConfig;

typedef struct tagServiceArgs {
    NodeServerConfig * config;
    //You can add other arguments here and initiate in main().
}ServiceArgs_t;

class NodeServiceImpl : public NodeService
{
public:
    NodeServiceImpl( ServiceArgs_t & app_args );
    virtual ~NodeServiceImpl();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int StartComponent( const magna::StartComponentRequest & req,
        magna::StartComponentResponse * resp );

    virtual int StopComponent( const magna::StopComponentRequest & req,
        magna::StopComponentResponse * resp );

private:
    ServiceArgs_t & args_;
};

