/* node_server_config.cpp

 Generated by phxrpc_pb2server from node.proto

*/

#include "node_server_config.h"

#include "node.pb.h"


NodeServerConfig::NodeServerConfig() {
}

NodeServerConfig::~NodeServerConfig() {
}

bool NodeServerConfig::Read(const char *config_file) {
    bool ret{ep_server_config_.Read(config_file)};

    if (0 == strlen(ep_server_config_.GetPackageName())) {
        ep_server_config_.SetPackageName(
magna::StartComponentRequest::default_instance().GetDescriptor()->file()->package().c_str());
    }

    return ret;
}

phxrpc::HshaServerConfig &NodeServerConfig::GetHshaServerConfig() {
    return ep_server_config_;
}

