/* node_main.cpp

 Generated by phxrpc_pb2server from node.proto

*/

#include <iostream>
#include <memory>
#include <unistd.h>
#include <signal.h>

#include "phxrpc_node_dispatcher.h"
#include "node_service_impl.h"
#include "node_server_config.h"

#include "phxrpc/rpc.h"
#include "phxrpc/msg.h"
#include "phxrpc/file.h"
#include "../AdminServer/admin_client.h"
#include <thread>
#include "NodeData.h"
#include <sys/epoll.h>
#include <errno.h> 


using namespace std;

void Dispatch(const phxrpc::BaseRequest *request,
              phxrpc::BaseResponse *response,
              phxrpc::DispatcherArgs_t *args) {
    ServiceArgs_t *service_args = (ServiceArgs_t *)(args->service_args);

    NodeServiceImpl service(*service_args);
    NodeDispatcher dispatcher(service, args);

    phxrpc::BaseDispatcher<NodeDispatcher> base_dispatcher(
            dispatcher, NodeDispatcher::GetMqttFuncMap(),
            NodeDispatcher::GetURIFuncMap());
    if (!base_dispatcher.Dispatch(request, response)) {
        response->DispatchErr();
    }
}

void ShowUsage(const char *program) {
    printf("\n");
    printf("Usage: %s [-c <config>] [-d] [-l <log level>] [-v]\n", program);
    printf("\n");

    exit(0);
}

AdminClient * g_adminProxy;
bool g_hbShouldRun = true;

void NodeHbFunc()
{
	NodeData * nodeData = NodeData::GetInstance();
	printf("\nNode heatbeat thread start running...\n");
	magna::NodeHeartbeatRequest req;
	magna::NodeHeartbeatResponse rsp;

	req.mutable_addr()->set_ip(nodeData->m_ip);
	req.mutable_addr()->set_port(nodeData->m_port);
	while (g_hbShouldRun)
	{
		sleep(2);
		req.mutable_load()->set_cpu(0.1); // TODO
		req.mutable_load()->set_disk(0.2); // TODO
		int ret = g_adminProxy->NodeHeatbeat(req, &rsp);
		if (0 != ret)
		{
			printf("\nNode heatbeat failed, ret: %d\n", ret);
		}

		if (rsp.ack())
		{
			printf("\nNode heatbeat ack received\n");
			// 更新节点数据
		}
		else
		{
			printf("\nNode heatbeat response ERROR. msg:%s\n", rsp.msg().c_str());
		}
	}
	printf("\nNode heatbeat thread stopped...\n");
	return;
}

bool testAdminEcho()
{
	g_adminProxy = new AdminClient;
	//AdminClient ac;
	google::protobuf::StringValue req;
	google::protobuf::StringValue resp;
	req.set_value("Access AdminServer Success");
	int ret = g_adminProxy->PhxEcho(req, &resp);
	printf("AdminServer.PhxEcho return %d\n", ret);
	printf("resp: {\n%s}\n", resp.DebugString().c_str());
	return ret == 0;
}

int AtopThreadFunc()
{
	struct epoll_event ev;                     //事件临时变量  
	const int MAXEVENTS = 1024;                //最大事件数  
	struct epoll_event events[MAXEVENTS];      //监听事件数组  
	int ret, pid;
	int pipe_fd[2];
	if ((ret = pipe(pipe_fd)) < 0)
	{
		cout << "create pipe fail:" << ret << ",errno:" << errno << endl;
		return -1;
	}
	ev.data.fd = pipe_fd[0];        //设置监听文件描述符，读端  
	ev.events = EPOLLIN | EPOLLET;    //设置要处理的事件类型  
	int epfd = epoll_create(MAXEVENTS);
	ret = epoll_ctl(epfd, EPOLL_CTL_ADD, pipe_fd[0], &ev);
	if (ret != 0)
	{
		cout << "epoll_ctl fail:" << ret << ",errno:" << errno << endl;
		close(pipe_fd[0]);
		close(pipe_fd[1]);
		close(epfd);
		return -1;
	}
	if ((pid = fork()) > 0)
	{
		string atopReport;
		while (g_hbShouldRun)
		{
			int count = epoll_wait(epfd, events, MAXEVENTS, 500);
			if (count == 0)// 超时，处理上一轮的数据
			{
				if (atopReport.empty())
				{
					continue;
				}
				printf("%s", atopReport.c_str());
				// TODO 处理监控数据，更新到NodeData中
				atopReport.clear();
			}
			char readBuffer[2048] = {};
			for (int i = 0; i < count; i++)
			{
				if ((events[i].data.fd == pipe_fd[0]) && (events[i].events&EPOLLIN))
				{
					read(pipe_fd[0], readBuffer, sizeof(readBuffer));
					atopReport.append(readBuffer);
					//printf("%s", readBuffer);
				}
			}
		}
		
		close(pipe_fd[1]);
		close(pipe_fd[0]);
		close(epfd);
		cout << "parent close read pipe" << endl;

	}
	else if (pid == 0)
	{
		close(pipe_fd[0]);//关闭读端
		if (dup2(pipe_fd[1], STDOUT_FILENO) != STDOUT_FILENO)//子进程的输出重定向到管道的输入
		{
			printf("重定向失败！");
			exit(0);
		}
		close(pipe_fd[1]);
		execlp("atop", "atop", "-o", NULL);
	}

	return 0;
}

int main(int argc, char **argv) {
    const char *config_file{nullptr};
    bool daemonize{false};
    int log_level{-1};
    extern char *optarg;
    int c;
    while (EOF != (c = getopt(argc, argv, "c:vl:d"))) {
        switch (c) {
            case 'c' : config_file = optarg; break;
            case 'd' : daemonize = true; break;
            case 'l' : log_level = atoi(optarg); break;

            case 'v' :
            default: ShowUsage(argv[0]); break;
        }
    }

    if (daemonize) phxrpc::ServerUtils::Daemonize();

    assert(signal(SIGPIPE, SIG_IGN) != SIG_ERR);

    //set customize log/monitor
    //phxrpc::setlog(openlog, closelog, vlog);
    //phxrpc::MonitorFactory::SetFactory(new YourSelfsMonitorFactory());

    if (nullptr == config_file) ShowUsage(argv[0]);

    NodeServerConfig config;
	if (!config.Read(config_file))
	{
		ShowUsage(argv[0]);
	}
	else
	{
		NodeData::GetInstance()->Init(config.GetHshaServerConfig().GetBindIP(), config.GetHshaServerConfig().GetPort());
	}
	

    if (log_level > 0) config.GetHshaServerConfig().SetLogLevel(log_level);

    phxrpc::openlog(argv[0], config.GetHshaServerConfig().GetLogDir(),
            config.GetHshaServerConfig().GetLogLevel());

	// 检查AdminServer是否可用
	AdminClient::Init("../AdminServer/admin_client.conf");
	bool adminOK = testAdminEcho();
	if (adminOK)
	{
		// 注册节点
		magna::RegisterNodeRequest req;
		magna::RegisterNodeResponse rsp;
		req.mutable_addr()->set_ip(NodeData::GetInstance()->m_ip);
		req.mutable_addr()->set_port(NodeData::GetInstance()->m_port);
		int ret = g_adminProxy->RegisterNode(req, &rsp);
		printf("AdminServer.RegisterNode return %d\n", ret);
		printf("resp: \n{\n%s\n}\n", rsp.DebugString().c_str());
	}

	// 启动心跳线程
	std::thread hb(NodeHbFunc);

	// 启动atop监控线程
	std::thread atop(AtopThreadFunc);

    ServiceArgs_t service_args;
    service_args.config = &config;

    phxrpc::HshaServer server(config.GetHshaServerConfig(), Dispatch, &service_args);
    server.RunForever();

    phxrpc::closelog();

    return 0;
}

