/* node_tool_impl.h

 Generated by phxrpc_pb2tool from node.proto

*/

#pragma once

#include "phxrpc_node_tool.h"

#include <cstdio>


namespace phxrpc {


class OptMap;


}


class NodeToolImpl : public NodeTool {
  public:
    NodeToolImpl();
    virtual ~NodeToolImpl();

    virtual int PhxMqttConnect(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttPublish(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttDisconnect(phxrpc::OptMap &opt_map) override;
    virtual int PhxEcho(phxrpc::OptMap &opt_map) override;
    virtual int StartComponent(phxrpc::OptMap &opt_map) override;
    virtual int StopComponent(phxrpc::OptMap &opt_map) override;
};

