/* node_client.h

 Generated by phxrpc_pb2client from node.proto

*/

#pragma once

#include "node.pb.h"
#include "phxrpc/rpc.h"

class NodeClient
{
public:
    static bool Init( const char * config_file );

    static const char * GetPackageName();

public:
    NodeClient();
    ~NodeClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int StartComponent( const magna::StartComponentRequest & req,
        magna::StartComponentResponse * resp );

    int StopComponent( const magna::StopComponentRequest & req,
        magna::StopComponentResponse * resp );


};
