/* node_tool_impl.h

 Generated by phxrpc_pb2tool from node.proto

*/

#pragma once

#include <stdio.h>

#include "phxrpc_node_tool.h"
namespace phxrpc {
    class OptMap;
}

class NodeToolImpl : public NodeTool
{
public:
    NodeToolImpl();
    virtual ~NodeToolImpl();

    virtual int PHXEcho( phxrpc::OptMap & opt_map );

    virtual int StartComponent( phxrpc::OptMap & opt_map );

    virtual int StopComponent( phxrpc::OptMap & opt_map );

};

