/* admin_client.h

 Generated by phxrpc_pb2client from admin.proto

*/

#pragma once

#include "admin.pb.h"
#include "phxrpc/rpc.h"

class AdminClient
{
public:
    static bool Init( const char * config_file );

    static const char * GetPackageName();

public:
    AdminClient();
    ~AdminClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int RegisterNode( const magna::RegisterNodeRequest & req,
        magna::RegisterNodeResponse * resp );

    int NodeHeatbeat( const magna::NodeHeartbeatRequest & req,
        magna::NodeHeartbeatResponse * resp );

    int RegisterService( const magna::RegisterServiceRequest & req,
        magna::RegisterServiceResponse * resp );

    int ServiceHeatbeat( const magna::ServiceHeartbeatRequest & req,
        magna::ServiceHeartbeatResponse * resp );


};
