/* admin_server_config.cpp

 Generated by phxrpc_pb2server from admin.proto

*/

#include "admin_server_config.h"

#include "admin.pb.h"


AdminServerConfig::AdminServerConfig() {
}

AdminServerConfig::~AdminServerConfig() {
}

bool AdminServerConfig::Read(const char *config_file) {
    bool ret{ep_server_config_.Read(config_file)};

    if (0 == strlen(ep_server_config_.GetPackageName())) {
        ep_server_config_.SetPackageName(
magna::RegisterNodeRequest::default_instance().GetDescriptor()->file()->package().c_str());
    }

    return ret;
}

phxrpc::HshaServerConfig &AdminServerConfig::GetHshaServerConfig() {
    return ep_server_config_;
}

