/* admin_server_config.h

 Generated by phxrpc_pb2server from admin.proto

*/

#pragma once

#include "phxrpc/rpc.h"


class AdminServerConfig {
  public:
    AdminServerConfig();

    virtual ~AdminServerConfig();

    bool Read(const char *config_file);

    phxrpc::HshaServerConfig &GetHshaServerConfig();

  private:
    phxrpc::HshaServerConfig ep_server_config_;
};

