/* admin_tool_impl.h

 Generated by phxrpc_pb2tool from admin.proto

*/

#pragma once

#include "phxrpc_admin_tool.h"

#include <cstdio>


namespace phxrpc {


class OptMap;


}


class AdminToolImpl : public AdminTool {
  public:
    AdminToolImpl();
    virtual ~AdminToolImpl();

    virtual int PhxMqttConnect(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttPublish(phxrpc::OptMap &opt_map) override;
    virtual int PhxMqttDisconnect(phxrpc::OptMap &opt_map) override;
    virtual int PhxEcho(phxrpc::OptMap &opt_map) override;
    virtual int RegisterNode(phxrpc::OptMap &opt_map) override;
    virtual int NodeHeatbeat(phxrpc::OptMap &opt_map) override;
    virtual int RegisterService(phxrpc::OptMap &opt_map) override;
    virtual int ServiceHeatbeat(phxrpc::OptMap &opt_map) override;
    virtual int Handle(phxrpc::OptMap &opt_map) override;
    virtual int GetServiceTable(phxrpc::OptMap &opt_map) override;
};

