/* admin_service_impl.h

 Generated by phxrpc_pb2service from admin.proto

*/

#pragma once

#include "admin.pb.h"
#include "phxrpc_admin_service.h"

class AdminServerConfig;

typedef struct tagServiceArgs {
    AdminServerConfig * config;
    //You can add other arguments here and initiate in main().
}ServiceArgs_t;

class AdminServiceImpl : public AdminService
{
public:
    AdminServiceImpl( ServiceArgs_t & app_args );
    virtual ~AdminServiceImpl();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int RegisterNode( const magna::RegisterNodeRequest & req,
        magna::RegisterNodeResponse * resp );

    virtual int NodeHeatbeat( const magna::NodeHeartbeatRequest & req,
        magna::NodeHeartbeatResponse * resp );

    virtual int RegisterService( const magna::RegisterServiceRequest & req,
        magna::RegisterServiceResponse * resp );

    virtual int ServiceHeatbeat( const magna::ServiceHeartbeatRequest & req,
        magna::ServiceHeartbeatResponse * resp );

private:
    ServiceArgs_t & args_;
};

